### ISSUE TITLE
If you change server settings for a world for a second time it doesn't save. 

### ISSUE THREAD

**Issue by amarhany20** [StunlockStudios/vrising-dedicated-server-instructions#27]
I have hosted the world. then after one day I decided to decrease the sun time for testing. I found out it only changes the time in server settings in game before joining and the time showing too changes. but, sometimes we get burnt even during the night.

before it was day start 9. day end 17.

I changed it to day start 10 and day end 12. 

now at 15 for example, it is night but we still get burnt.

another example on another world, I have changed the resourcepowermultiplyer to 2 and created a new world, it is working and then I decided to test what will happen if I do it 10. and nothing new happens, only the number changes. Then I set it as 1. Still no diffrence in game. 

Does the server save the settings only when creating? and after that I can't change anything?

**Comment by aseme** [comment]
It looks like this has been fixed in the hot fix that was published today. https://store.steampowered.com/news/app/1604030/view/3218396837686301547

**Comment by amarhany20** [comment]
It is still happening for me unfortunatly and I have installed it yesterday even after the update...

anyways I stopped playing in this world, and playing in another world and if I alter any settings it doens't save I don't know why

**Comment by amarhany20** [comment]
https://www.reddit.com/r/vrising/comments/us53d8/comment/i92174r/?utm_source=share&utm_medium=web2x&context=3

Here is my problem
